/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
public interface ParserConstants {

  int EOF = 0;
  int LBRACE = 1;
  int RBRACE = 2;
  int LBRACK = 3;
  int RBRACK = 4;
  int LPAREN = 5;
  int RPAREN = 6;
  int COMMA = 7;
  int SEMI = 8;
  int DOT = 9;
  int EXCLAM = 10;
  int ASSIGN = 11;
  int AND = 12;
  int PLUS = 13;
  int MINUS = 14;
  int TIMES = 15;
  int LT = 16;
  int IF = 17;
  int INT = 18;
  int NEW = 19;
  int ELSE = 20;
  int MAIN = 21;
  int THIS = 22;
  int TRUE = 23;
  int VOID = 24;
  int CLASS = 25;
  int FALSE = 26;
  int WHILE = 27;
  int LENGTH = 28;
  int PUBLIC = 29;
  int RETURN = 30;
  int STAT = 31;
  int STRING = 32;
  int BOOLEAN = 33;
  int EXTENDS = 34;
  int SYSOPRNTL = 35;
  int ID = 36;
  int NUM = 37;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\";\"",
    "\".\"",
    "\"!\"",
    "\"=\"",
    "\"&&\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"<\"",
    "\"if\"",
    "\"int\"",
    "\"new\"",
    "\"else\"",
    "\"main\"",
    "\"this\"",
    "\"true\"",
    "\"void\"",
    "\"class\"",
    "\"false\"",
    "\"while\"",
    "\"length\"",
    "\"public\"",
    "\"return\"",
    "\"static\"",
    "\"String\"",
    "\"boolean\"",
    "\"extends\"",
    "\"System.out.println\"",
    "<ID>",
    "<NUM>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<token of kind 43>",
  };

}
