/* Generated By:JavaCC: Do not edit this line. NewParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface NewParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LBRACE = 1;
  /** RegularExpression Id. */
  int RBRACE = 2;
  /** RegularExpression Id. */
  int LBRACK = 3;
  /** RegularExpression Id. */
  int RBRACK = 4;
  /** RegularExpression Id. */
  int LPAREN = 5;
  /** RegularExpression Id. */
  int RPAREN = 6;
  /** RegularExpression Id. */
  int COMMA = 7;
  /** RegularExpression Id. */
  int SEMI = 8;
  /** RegularExpression Id. */
  int DOT = 9;
  /** RegularExpression Id. */
  int EXCLAM = 10;
  /** RegularExpression Id. */
  int ASSIGN = 11;
  /** RegularExpression Id. */
  int AND = 12;
  /** RegularExpression Id. */
  int PLUS = 13;
  /** RegularExpression Id. */
  int MINUS = 14;
  /** RegularExpression Id. */
  int TIMES = 15;
  /** RegularExpression Id. */
  int LT = 16;
  /** RegularExpression Id. */
  int IF = 17;
  /** RegularExpression Id. */
  int INT = 18;
  /** RegularExpression Id. */
  int NEW = 19;
  /** RegularExpression Id. */
  int ELSE = 20;
  /** RegularExpression Id. */
  int MAIN = 21;
  /** RegularExpression Id. */
  int THIS = 22;
  /** RegularExpression Id. */
  int TRUE = 23;
  /** RegularExpression Id. */
  int VOID = 24;
  /** RegularExpression Id. */
  int CLASS = 25;
  /** RegularExpression Id. */
  int FALSE = 26;
  /** RegularExpression Id. */
  int WHILE = 27;
  /** RegularExpression Id. */
  int LENGTH = 28;
  /** RegularExpression Id. */
  int PUBLIC = 29;
  /** RegularExpression Id. */
  int RETURN = 30;
  /** RegularExpression Id. */
  int STAT = 31;
  /** RegularExpression Id. */
  int STRING = 32;
  /** RegularExpression Id. */
  int BOOLEAN = 33;
  /** RegularExpression Id. */
  int EXTENDS = 34;
  /** RegularExpression Id. */
  int SYSOPRNTL = 35;
  /** RegularExpression Id. */
  int ID = 36;
  /** RegularExpression Id. */
  int NUM = 37;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\";\"",
    "\".\"",
    "\"!\"",
    "\"=\"",
    "\"&&\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"<\"",
    "\"if\"",
    "\"int\"",
    "\"new\"",
    "\"else\"",
    "\"main\"",
    "\"this\"",
    "\"true\"",
    "\"void\"",
    "\"class\"",
    "\"false\"",
    "\"while\"",
    "\"length\"",
    "\"public\"",
    "\"return\"",
    "\"static\"",
    "\"String\"",
    "\"boolean\"",
    "\"extends\"",
    "\"System.out.println\"",
    "<ID>",
    "<NUM>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<token of kind 43>",
  };

}
